version: "3.9"

services:
  web:
    build: .
    container_name: zentryx_web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    restart: always
    environment:
      - DB_HOST=zentryx_db
      - DB_USER=root
      - DB_PASSWORD=1
      - DB_NAME=zentryx

  db:
    image: mariadb:10.4
    container_name: zentryx_db
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE: zentryx
      MARIADB_USER: root
      MARIADB_PASSWORD: 1
    volumes:
      - ./db_data:/var/lib/mysql
      - ./zentryx.sql:/docker-entrypoint-initdb.d/zentryx.sql
    ports:
      - "3306:3306"

volumes:
  db_data: